version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        - APP_PORT=${APP_PORT:-8000}
        - APP_HOST=${APP_HOST:-0.0.0.0}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

networks:
  default:
    driver: bridge
